# DS2002 · Cleaning Gauntlet

**Lab — 2026-09-25 · Fall 2026**  

---

## Lab 05 — Cleaning Gauntlet

Three hundred rows, generated messy. This is the first dataset in the course you cannot eyeball, which means you have to work from counts and assertions rather than from looking at the table and deciding it seems fine.

Deliverables: a clean frame, a decision log, a set of assertions that pass, and one business number at the end — revenue by category — that you would be willing to defend.

Keep the log as you go. Reconstructing it afterward is much harder than writing one line per step, and the write-up at the end depends on it.

### The log

Run this first, then call `log(...)` after each cleaning step.

In [1]:
DECISIONS = []

def log(step, decision, rows_affected):
    DECISIONS.append({'step': step, 'decision': decision, 'rows': rows_affected})
    print(f'[{step}] {decision} ({rows_affected} row(s))')

In [2]:
import pandas as pd, numpy as np
from io import StringIO
rng = np.random.default_rng(5)
items = ['Cheeseburger','cheese burger','Foam Finger','foam finger','Rain Poncho','rain poncho']
cats = ['Food','food','Merch','Apparel','RainGear','rain-gear']
rows = []
for i in range(300):
    rows.append({
        'order_id': i,
        'item': rng.choice(items),
        'category': rng.choice(cats),
        'qty': rng.choice([1,2,3,-1,np.nan], p=[.5,.25,.15,.05,.05]),
        'price': rng.choice(['$7.50','7.5','$12.00','24','6.0']),
    })
df = pd.DataFrame(rows)
df = pd.concat([df, df.sample(15, random_state=1)])  # inject dupes
df.head()

   order_id           item  category  qty   price
0         0    Rain Poncho  RainGear  3.0  $12.00
1         1    foam finger   Apparel  1.0     7.5
2         2  cheese burger     Merch  1.0   $7.50
3         3   Cheeseburger      Food  NaN   $7.50
4         4  cheese burger   Apparel  1.0     7.5

### TODO 1 — drop duplicates

In [3]:
# TODO
before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
assert df['order_id'].is_unique
log('dedupe', 'dropped exact duplicate rows (injected by df.sample)', before - len(df))

[dedupe] dropped exact duplicate rows (injected by df.sample) (15 row(s))

### TODO 2 — clean `price` -> float

In [4]:
# TODO
print(df['price'].value_counts())
df['price'] = df['price'].str.replace('$', '', regex=False).str.strip().astype(float)
log('price', "stripped '$' and cast to float; '7.5' and '$7.50' now both 7.5", len(df))

price
6.0       67
$12.00    65
$7.50     59
7.5       58
24        51
Name: count, dtype: int64
[price] stripped '$' and cast to float; '7.5' and '$7.50' now both 7.5 (300 row(s))

### TODO 3 — `qty` -> numeric, drop rows with missing/negative qty

In [5]:
# TODO
df['qty'] = pd.to_numeric(df['qty'], errors='coerce')
n_nan = df['qty'].isna().sum()
n_neg = (df['qty'] < 0).sum()
df = df[df['qty'].notna() & (df['qty'] >= 1)].copy()
df['qty'] = df['qty'].astype(int)
log('qty', f'dropped {n_nan} missing and {n_neg} negative qty rows', n_nan + n_neg)

[qty] dropped 12 missing and 13 negative qty rows (25 row(s))

### TODO 4 — canonicalize `item`

Six spellings, three real products. Start by listing what you actually have, then build the mapping from that list rather than from memory.

```python
print(df['item'].value_counts())
ITEM_MAP = {...}
```

In [6]:
# TODO: inspect the variants, build a mapping dict, apply it, log the collapse
print(df['item'].value_counts())
ITEM_MAP = {
    'Cheeseburger': 'Cheeseburger', 'cheese burger': 'Cheeseburger',
    'Foam Finger': 'Foam Finger',   'foam finger': 'Foam Finger',
    'Rain Poncho': 'Rain Poncho',   'rain poncho': 'Rain Poncho',
}
unmapped = set(df['item']) - set(ITEM_MAP)
assert not unmapped, unmapped
changed = (df['item'] != df['item'].map(ITEM_MAP)).sum()
df['item'] = df['item'].map(ITEM_MAP)
log('item', '6 spellings -> 3 products via ITEM_MAP', changed)

item
Foam Finger      57
Rain Poncho      49
cheese burger    44
Cheeseburger     43
rain poncho      42
foam finger      40
Name: count, dtype: int64
[item] 6 spellings -> 3 products via ITEM_MAP (126 row(s))

### TODO 5 — normalize `category`

Same approach. Note that `Apparel` and `Merch` are a business decision, not a string problem — decide and log it.

In [7]:
# TODO
print(df['category'].value_counts())
CAT_MAP = {
    'Food': 'Food', 'food': 'Food',
    'Merch': 'Merch', 'Apparel': 'Merch',   # business decision: fold Apparel into Merch
    'RainGear': 'Rain Gear', 'rain-gear': 'Rain Gear',
}
assert not set(df['category']) - set(CAT_MAP)
changed = (df['category'] != df['category'].map(CAT_MAP)).sum()
df['category'] = df['category'].map(CAT_MAP)
log('category', 'normalized case/hyphens; merged Apparel into Merch (business call)', changed)

category
Food         51
Merch        51
rain-gear    45
food         44
Apparel      43
RainGear     41
Name: count, dtype: int64
[category] normalized case/hyphens; merged Apparel into Merch (business call) (173 row(s))

### TODO 6 — prove it's clean

**TODO:** uncomment these and add two more assertions of your own — one about the item names and one about the categories.

In [8]:
assert df.duplicated().sum() == 0
assert df['qty'].min() >= 1
assert df['price'].dtype == float
assert set(df['item']) == {'Cheeseburger', 'Foam Finger', 'Rain Poncho'}
assert set(df['category']) == {'Food', 'Merch', 'Rain Gear'}
# TODO: assert something about item
# TODO: assert something about category
print('clean:', df.shape)

clean: (275, 5)

### TODO 7 — the number you would report

**TODO:** add a `revenue` column, then print revenue by category, highest first, plus the overall total. Round money to two decimals.

Then, in one sentence, state what you would tell a vendor to stock more of.

In [9]:
# TODO
df['revenue'] = (df['qty'] * df['price']).round(2)
by_cat = df.groupby('category')['revenue'].sum().round(2).sort_values(ascending=False)
print(by_cat)
print('TOTAL:', round(df['revenue'].sum(), 2))

category
Food         1656.0
Merch        1572.0
Rain Gear    1512.0
Name: revenue, dtype: float64
TOTAL: 4740.0

**What I would tell the vendor:** _..._

### TODO 8 — read back your log

In [10]:
import pandas as pd
pd.DataFrame(DECISIONS)

       step                                           decision  rows
0    dedupe  dropped exact duplicate rows (injected by df.s...    15
1     price  stripped '$' and cast to float; '7.5' and '$7....   300
2       qty        dropped 12 missing and 13 negative qty rows    25
3      item             6 spellings -> 3 products via ITEM_MAP   126
4  category  normalized case/hyphens; merged Apparel into M...   173

### Write-up

Two parts.

**a)** Which cleaning step changed your revenue total the most? Give the number before and after that step, not a description.


**b)** Pick one decision you made where a reasonable person could have chosen differently. State the other choice, what it would have done to your reported revenue, and why you went the way you did.

I compared total revenue after each step. At the start, with prices parsed, NaN qty skipped, and negatives included, it was $4,852.50. Deduplication brought it to $4,594.50, a drop of $258, which is the biggest change. Dropping negative qty raised it to $4,740.00, a gain of $145.50, because the negative rows had been subtracting revenue. NaN rows contributed $0 either way. The item and category mapping didn't change the total.

Apparel vs Merch: If you keep them separate, you get Food $1,656, Rain Gear $1,512, Merch $856.50, and Apparel $715.50. The total is the same, but Merch drops from #2 to #3.